### ISSUE TITLE
Building image with tilemaker-debian.Dockerfile failed

### ISSUE THREAD

**Issue by skaringa** [versatiles-org/versatiles-docker#13]
I run the command to build tilemaker-debian.Dockerfile as described in the README: 

`docker build --file=docker/tilemaker-debian.Dockerfile --tag=test .`

However it fails:

```
STEP 5/7: RUN git clone --depth 1 -q --branch versatiles https://github.com/versatiles-org/shortbread-tilemaker shortbread-tilemaker
--> b37392bb1be

STEP 6/7: RUN cd shortbread-tilemaker && ./get-shapefiles.sh
/bin/sh: 1: ./get-shapefiles.sh: not found
```

Indeed, if I look at https://github.com/versatiles-org/shortbread-tilemaker branch versatiles, then there is no script get-shapefiles.sh

**Comment by MichaelKreil** [comment]
OK, we had some problems with our "improvements" to the shortbread configuration of tilemaker. In the end we gave up, abandoned our fork and went back to the original https://github.com/shortbread-tiles/shortbread-tilemaker. This fixed the problem.
